config/routes.rb
Rails.application.routes.draw do

  resources :transaction_records, only: [:index]
  resources :transactions, only: [:create, :update]

  devise_for :users

  scope "/admin" do
    resources :users, except: [:index, :destroy]
  end

  authenticated :user, ->(u) { u.admin? } do
    root to: 'users#adminpanel', as: :admin_root
  end
  
  authenticated :user, ->(u) { u.trader? } do
    root to: 'transactions#index', as: :trader_root
  end

  root to: 'transactions#index'
  
  get 'get_stock_quote', to: 'stocks#get_quote'
  get 'edit_transaction', to: 'transactions#edit'
  get 'my_portfolio', to: 'transactions#index'
  
  get 'adminpanel', to: 'users#adminpanel'
  get 'approve', to: 'users#approve'
  patch 'approve_trader', to: 'users#approve_trader'

  namespace :admin do
    resources :transaction_records, only: [:index]
  end

end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :transactions
  has_many :users, through: :transactions

  #add validations here

  def self.new_quote(stock_symbol)
    client = IEX::Api::Client.new(publishable_token: Rails.application.credentials.iex_client[:public_key],
                                  secret_token: Rails.application.credentials.iex_client[:secret_key],
                                  endpoint: 'https://cloud.iexapis.com/v1') #initializer
    

    begin
      quote = client.quote(stock_symbol)
      new(symbol: stock_symbol, name: quote.company_name, latest_price: quote.latest_price)
    rescue IEX::Errors::SymbolNotFoundError
      return nil
    end

  end

  def self.check_db(symbol) #modify this // refer to NOTES
    where(symbol: symbol).first
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  

  def get_quote
    
    if params[:stock].present?
      
      stock = Stock.check_db(params[:stock])
      if stock
        @owned_stock = current_user.transactions.where(stock_id: stock.id).first
      end
      
      @stock = Stock.new_quote(params[:stock])
      if @stock
        respond_to do |format|
          format.js { render partial: 'transactions/form' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Please enter a valid stock symbol to search."
          format.js { render partial: 'transactions/form' }
        end
      end
      
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a stock symbol to search."
        format.js { render partial: 'transactions/form' }
      end
    end

  end

end

app/views/stocks/_list.html.erb
<div class="row">
  <div class="col-9">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Stock Symbol</th>
          <th scope="col">Company Name</th>
          <th scope="col">Shares</th>
          <th scope="col">Price</th>
          <th scope="col">Total</th>
          <th scope="col"></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <% @owned_stocks.each do |owned_stock| %>
          <tr>
            <th scope="row"><%= owned_stock.stock.symbol %></th>
            <td><%= owned_stock.stock.name%></td>
            <td><%= stock_shares = owned_stock.shares %></td>
            <td><%= latest_price = owned_stock.stock.latest_price %></td>
            <td><%= stock_shares * latest_price  %></td>
            <td>
              <%= form_tag edit_transaction_path, remote: true, method: :get do %>
                <%= hidden_field_tag :id, owned_stock.id %>
                <%= button_tag type: :submit, class: "btn btn-success btn-sm" do %>
                  <%= 'Buy' %>
                <% end %>
              <% end %>
            </td>
            <td>
              <%= form_tag edit_transaction_path, remote: true, method: :get do %>
                <%= hidden_field_tag :transaction_type_sell, "True" %>
                <%= hidden_field_tag :id,  owned_stock.id %>
                <%= button_tag type: :submit, class: "btn btn-danger btn-sm" do %>
                  <%= 'Sell' %>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>