config/routes.rb
Rails.application.routes.draw do

  resources :transaction_records, only: [:index]
  resources :transactions, only: [:create, :update]

  devise_for :users

  scope "/admin" do
    resources :users, except: [:index, :destroy]
  end

  authenticated :user, ->(u) { u.admin? } do
    root to: 'users#adminpanel', as: :admin_root
  end
  
  authenticated :user, ->(u) { u.trader? } do
    root to: 'transactions#index', as: :trader_root
  end

  root to: 'transactions#index'
  
  get 'get_stock_quote', to: 'stocks#get_quote'
  get 'edit_transaction', to: 'transactions#edit'
  get 'my_portfolio', to: 'transactions#index'
  
  get 'adminpanel', to: 'users#adminpanel'
  get 'approve', to: 'users#approve'
  patch 'approve_trader', to: 'users#approve_trader'

  namespace :admin do
    resources :transaction_records, only: [:index]
  end

end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :transactions
  has_many :stocks, through: :transactions
  has_many :transaction_records

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  def stock_already_owned?(symbol)
    stock = Stock.check_db(symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end
  
  def trader?
    !admin?
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_admin

  def adminpanel
    @users = User.where(admin: false)
  end

  def approve
    @users = User.where(admin: false, approved: false)
  end

  # def index
  #   @users = User.where(admin: false)
  # end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
        redirect_to adminpanel_path
    else
        render :new
    end
  end

  # GET /users/:id
  def show
    @user = User.find(params[:id])
  end

  # GET /users/:id/edit
  def edit
    @user = User.find(params[:id])
  end

  # PATCH /users/:id
  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to adminpanel_path
    else
      render :edit
    end

  end     

  # DELETE /users/:id
  # def destroy
  #   if current_user.admin?
  #     @user = User.find(params[:id])
  #     @user.destroy
  #   end

  #   redirect_to adminpanel_path
  # end

  def approve_trader
    user = User.find(params[:user_id])
    user.update(approved: true)
    flash[:notice] = "User has been approved!"
    TraderAccountApprovalMailer.with(trader: user).trader_account_approved.deliver_now
    redirect_to approve_path
  end

  private

  def require_admin
    if !current_user.admin?
      flash[:alert] = "Only admin can perform such action."
      redirect_to my_portfolio_path
    end
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :approved)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<body>
        <%= form_with model: user do |f| %>
            <p>
                <% if user.errors.any? %>
                    <ul>
                        <% user.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                        <% end %>
                    </ul>
                <% end %>
            </p>
    
            <div class="form-group">
                <%= f.label :email %>
                <%= f.email_field :email, autofocus: true, autocomplete: 'email', class: 'form-control' %>
            </div>

            <div class="form-group">
                <%= f.label :password %>
                <%= f.password_field :password, autocomplete: 'current-password', class: 'form-control' %>

                <% if @minimum_password_length %>
                    <small class="form-text text-muted"><%= t('devise.shared.minimum_password_length', count: @minimum_password_length) %></small>
                <% end %>
            </div>

            <div class="form-group">
                <%= f.label :password_confirmation %>
                <%= f.password_field :password_confirmation, autocomplete: 'current-password', class: 'form-control' %>
            </div>

            <p>
                <%= f.label :approved %><br>
                <%= f.check_box :approved %>
            </p>

            <div class="form-group">
                <%= f.submit %>
            </div>
        <% end %>
</body>

app/views/users/adminpanel.html.erb
<h1>List of all traders</h1>
<div class="row">
  <div class="col-9">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Trader Email</th>
          <th scope="col">Trader Account Status</th>
          <th scope="col"></th>
          <th scope="col"</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <th scope="row"><%= link_to user.email, user, class: "user-email" %></th>
            <td>
              <% if user.approved? %>
                Approved
              <% else %>
                Pending approval
              <% end %>
            </td>
            <td><%= link_to "Show", user %></td>
            <td><%= link_to "Edit", edit_user_path(user) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/approve.html.erb
<h1>Trader Accounts with Pending Approval</h1>
<div class="row">
  <div class="col-9">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Trader Email</th>
          <th scope="col"></th>

        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <th scope="row"><%= link_to user.email, user, class: "user-email" %></th>
            <td>
                <%= form_with(url: approve_trader_path, method: :patch, class: "rounded", local: true) do |f| %>
                    <%= f.hidden_field :user_id, :value => user.id %>
                    <%= f.submit "Approve", class: "btn btn-success btn-sm" %>
                <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/edit.html.erb
<div class="mainContainer">
    
    <div class="formContainer">
        <div class="pageTitle">edit user</div>
        <%= render "form", user: @user %>
    </div>

</div>

app/views/users/new.html.erb
<div class="mainContainer">

    <div class="formContainer">
        <h1>Create trader account</h1>
        <%= render "form", user: @user %>
    </div>
        
</div>

app/views/users/show.html.erb
<div class="mainContainer">
    
    <div class="formContainer">
        <div class="pageTitle"><%= @user.email %></div>
    </div>

    <div class="allButtons">
        <div class="smallLink">
            <%= link_to "Edit", edit_user_path(@user) %>
        </div>
    </div>
</div>