config/routes.rb
Rails.application.routes.draw do

  resources :transaction_records, only: [:index]
  resources :transactions, only: [:create, :update]

  devise_for :users

  scope "/admin" do
    resources :users, except: [:index, :destroy]
  end

  authenticated :user, ->(u) { u.admin? } do
    root to: 'users#adminpanel', as: :admin_root
  end
  
  authenticated :user, ->(u) { u.trader? } do
    root to: 'transactions#index', as: :trader_root
  end

  root to: 'transactions#index'
  
  get 'get_stock_quote', to: 'stocks#get_quote'
  get 'edit_transaction', to: 'transactions#edit'
  get 'my_portfolio', to: 'transactions#index'
  
  get 'adminpanel', to: 'users#adminpanel'
  get 'approve', to: 'users#approve'
  patch 'approve_trader', to: 'users#approve_trader'

  namespace :admin do
    resources :transaction_records, only: [:index]
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  require 'bigdecimal/util'
  before_action :disallow_admin
  before_action :disallow_unapproved_trader, only: [:create, :edit, :update]
  before_action :require_stock_shares, only: [:create, :update]
  before_action :restrict_stock_selling, only: :update

  def index
    @owned_stocks = current_user.transactions
    render :my_portfolio
  end

  def create
    stock = Stock.check_db(transaction_params[:symbol]) #lines 14 to 18 can be done using find_or_create_by
    if stock.blank?
      stock = Stock.new_quote(transaction_params[:symbol])
      stock.save
    end
    
    @transaction = current_user.transactions.create(stock: stock, shares: transaction_params[:shares])
    @transaction_record = current_user.transaction_records.create(stock_symbol: stock.symbol, company_name: stock.name, shares: transaction_params[:shares], price: stock.latest_price, transaction_type: "buy")
    flash[:notice] = "Purchase successful!"
    redirect_to my_portfolio_path
  end

  def edit
    if params[:transaction_type_sell].present?
      @transaction_type_sell = params[:transaction_type_sell]
    end

    @owned_stock = Transaction.find(params[:id])
    @stock = @owned_stock.stock

    respond_to do |format|
      format.js { render partial: 'transactions/form' }
    end
    
  end

  def update
    @transaction = Transaction.find(params[:id])
    stock = @transaction.stock

    if params[:transaction_type_sell] == "True"
      updated_shares = @transaction.shares - transaction_params[:shares].to_d
      remove_stock_from_transactions(@transaction, stock, transaction_params[:shares]) if updated_shares == 0 
      transaction_type = "sell"
      flash_message = "Selling successful!"
    else
      updated_shares = @transaction.shares + transaction_params[:shares].to_d
      transaction_type = "buy"
      flash_message = "Purchase successful!"
    end
    
    begin
      @transaction.update(shares: updated_shares)
      @transaction_record = current_user.transaction_records.create(stock_symbol: stock.symbol, company_name: stock.name, shares: transaction_params[:shares], price: stock.latest_price, transaction_type: transaction_type)
      flash[:notice] = flash_message
      redirect_to my_portfolio_path
    rescue FrozenError
      flash[:notice] = "Selling successful!"
      redirect_to my_portfolio_path
    end
  end

  private

  def transaction_params
    params.require(:transaction).permit(:symbol, :shares)
  end

  def disallow_unapproved_trader
		if !current_user.approved?
			flash[:alert] = "Only approved traders can trade stocks."
			redirect_to my_portfolio_path
		end
	end

  def remove_stock_from_transactions(transaction, stock, shares)
    transaction.destroy
    current_user.transaction_records.create(stock_symbol: stock.symbol, company_name: stock.name, shares: shares, price: stock.latest_price, transaction_type: "sell")
  end

  def restrict_stock_selling
    if params[:transaction_type_sell] == "True" && transaction_params[:shares].to_d > Transaction.find(params[:id]).shares
      flash[:alert] = "You cannot sell more stocks than you have."
      redirect_to my_portfolio_path
    end
  end

  def require_stock_shares
    if !transaction_params[:shares].present?
      flash[:alert] = "Please input number of shares you want to buy/sell."
      redirect_to my_portfolio_path
    end
  end

end

app/helpers/transactions_helper.rb
module TransactionsHelper

  def build_form_with_attributes(owned_stock, stock)
    attributes = {}

    if current_user.stock_already_owned?(stock.symbol)
      attributes[:location] = "/transactions/#{owned_stock.id}"
      attributes[:method_type] = :patch
    else
      attributes[:location] = :transactions
      attributes[:method_type] = :post
    end

    if @transaction_type_sell == "True"
      attributes[:text_field_placeholder] =  "Number of shares to sell..."
      attributes[:submit_button_label] = "Sell #{stock.name}"
    else
      attributes[:text_field_placeholder] =  "Number of shares to buy..."
      attributes[:submit_button_label] = "Buy #{stock.name}"
    end
    
    attributes
    
  end

end

app/views/transactions/_form.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>

<% if @stock %>
  <div class="card card-header results-block">
    <strong>Symbol: </strong><%= @stock.symbol %> |
    <strong>Company Name: </strong><%= @stock.name %> |
    <strong>Price: </strong><%= @stock.latest_price %>

    <% form_attributes = build_form_with_attributes(@owned_stock, @stock) %>

    <%= form_with(scope: :transaction, url: form_attributes[:location], method: form_attributes[:method_type], class: "rounded", local: true) do |f| %>
      <%= f.hidden_field :symbol, :value => @stock.symbol %>
      <% if @transaction_type_sell == "True" %>
        <%= hidden_field_tag :transaction_type_sell, "True" %>
      <% end %>
      <%= f.text_field :shares, class: "form-control shadow rounded", placeholder: form_attributes[:text_field_placeholder], id: "text-field-buy-stocks" %>
      <%= f.submit form_attributes[:submit_button_label], class: "btn btn-success btn-sm" %>
    <% end %>
    
  </div>
<% end %>

app/views/transactions/_form.js.erb
document.querySelector('#quote').innerHTML = '<%= j render 'transactions/form.html' %>'

app/views/transactions/_quote.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>

<% if @stock %>
  <div class="card card-header results-block">
    <strong>Symbol: </strong><%= @stock.symbol %> |
    <strong>Company Name: </strong><%= @stock.name %> |
    <strong>Price: </strong><%= @stock.latest_price %>
    <% if current_user.stock_already_owned?(@stock.symbol) %>
      <% location = "/transactions/#{@owned_stock.id}" %>
      <% method_type = :patch  %>
    <% else %>
      <% location = :transactions %>
      <% method_type = :post  %>
    <% end %>
    <% if @transaction_type_sell == "True" %>
      <% text_field_placeholder =  "Number of shares to sell..." %>
      <% submit_button_label = "Sell #{@stock.name}" %>
    <% else %>
      <% text_field_placeholder =  "Number of shares to buy..." %>
      <% submit_button_label = "Buy #{@stock.name}" %>
    <% end %>
    <%= form_with(url: location, method: method_type, class: "rounded", local: true) do |f| %>
      <%= f.hidden_field :symbol, :value => @stock.symbol %>
      <% if @transaction_type_sell == "True" %>
        <%= hidden_field_tag :transaction_type_sell, "True" %>
      <% end %>
      <%= f.text_field :shares, class: "form-control shadow rounded", placeholder: text_field_placeholder, id: "text-field-buy-stocks" %>
      <%= f.submit submit_button_label, class: "btn btn-success btn-sm" %>
    <% end %>
  </div>
<% end %>

app/views/transactions/my_portfolio.html.erb
<h1>My portfolio</h1>

<div class='search-area'>
  <h3>Request Stock Quote</h3>
  <h6>Enter the symbol of the stock you are interested in.</h6>
  <%= form_tag get_stock_quote_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: "ex. MSFT, AAPL, AMZN", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3">
        <%= button_tag type: :submit, class: "btn btn-success btn-lg" do %>
          <%= 'Get Quote' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="quote">

</div>
<% if !@owned_stocks.empty? %>
  <%= render 'stocks/list' %>
<% end %>