config/routes.rb
Rails.application.routes.draw do

  resources :transaction_records, only: [:index]
  resources :transactions, only: [:create, :update]

  devise_for :users

  scope "/admin" do
    resources :users, except: [:index, :destroy]
  end

  authenticated :user, ->(u) { u.admin? } do
    root to: 'users#adminpanel', as: :admin_root
  end
  
  authenticated :user, ->(u) { u.trader? } do
    root to: 'transactions#index', as: :trader_root
  end

  root to: 'transactions#index'
  
  get 'get_stock_quote', to: 'stocks#get_quote'
  get 'edit_transaction', to: 'transactions#edit'
  get 'my_portfolio', to: 'transactions#index'
  
  get 'adminpanel', to: 'users#adminpanel'
  get 'approve', to: 'users#approve'
  patch 'approve_trader', to: 'users#approve_trader'

  namespace :admin do
    resources :transaction_records, only: [:index]
  end

end

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class='alert alert-success'>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
      </button>
		<%= notice %>
	</div>
<% end %>
<% if alert %>
	<div class='alert alert-danger'>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
      </button>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="#">JGtrade</a>

    <% if current_user %>

      <% if current_user.admin? %>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to "Home", adminpanel_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Add trader", new_user_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Approve trader", approve_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Transactions", admin_transaction_records_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
        
      <% else %>  
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item <%= 'active' if request.path == my_portfolio_path %>">
              <%= link_to "My Portfolio", my_portfolio_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Transactions", transaction_records_path, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"><%= current_user.email %></a>
            </li>
          </ul>
        </div>
      <% end %>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to 'Log out', destroy_user_session_path, class: "btn btn-danger", method: :delete %>
          </li>
        </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JGTrade</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>  
  </body>
</html>